tokens = [
    "zqylan",
    "vothrek",
    "murgash",
    "drelbo",
    "kyrvax",
    "plontu",
    "sarnick",
    "tuvvel",
    "wexomi",
    "glarpen",
    "brummok",
    "nesquat",
    "chodvir",
    "faltrix",
    "ombregu",
    "jastrel",
    "quenlop",
    "ridvash",
    "skelnu",
    "thurgin",
    "ubrikol",
    "yalmot",
    "ancholi",
    "biffrun",
    "cravlem",
    "dushkan",
    "ecrivo",
    "hulvary",
    "iskaren",
    "klombu",
    "lyxeren",
    "mardush",
    "nubvile",
    "oqualth",
    "prevnusk",
    "raskombi",
    "shelvrid",
    "tornibal",
    "umbrakel",
    "wolquist",
]
